# stats available at
# https://travis-ci.org/strukturag/libheif/
language: cpp
compiler:
  - clang
  - gcc
os:
  - osx
  - linux
dist: bionic
cache:
  directories:
    - '$HOME/.sonar/cache'
addons:
  apt:
    packages:
      - libde265-dev
      - libx265-dev
      - libaom-dev
  sonarcloud:
    organization: "cartoonfan"
    token: 
      secure: "Mcz25GLk02rQP9YSvbVPo7TzeuJUbEuphxeAaeb66qec9fyR4MU/J5diMgi0Pu2AX3K7ZEuKkXGGSZ9FqMl5B2V3koQ5SEtEXRPJxACeA60YUiZhtcNLffR0o79vvLoa1SHUJDfedyAZ+Vun9qGptHu/yjC0DbUBjL8IkAB1EEqRKDa3/sPiNBpspu7wdY0Aj7Y9Ag7mxyxS06WtNRVxog9vmPEFx6R73HDaqf1G4KpCLSF4ilR9utN0jxE4SAWwPLFcEhH9NjtWvyKNi3OUyGOG5Q3WVvshhgqK6Gm10zaPuK65xyEnNo3nnVJHJTSdpGmqg9Fej+z0FqAyCtMNTqmAObRhIMi5cnnx1m3b6VdNynDqPbhmgGEA2FMB8XpVTBJ7aU4YGmDmBE2nI8EyVK6bAoUEAug+Fvz0ntC5tOnx96qBugt7zRSbCTeL3R427zy6WoX4IlH8Jr79yXG8GugCoi2tPTLgRx3LZogYHpO4QqCBqvkgpWUxVsP3BxWTaFITVD/wQBuDZNhYrFsyTnuJIXk1r9iI4IekVaaj0qRN4jTmmPXNdTTPUygbgmty/8Zpqx/s/48yRfw60avwq5BSzlLcLlpGNrhr5loyQLvSemCacrHdWaBVksbyJ9OtYvVGXF+5fhyYVGJ/v1E6ktBouUDqKIDWhf7ezZlw4xE="

before_install:
- git fetch --unshallow

script:
  # Prepare the build system
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - if [ $TRAVIS_OS_NAME = osx ]; then build-wrapper-macosx-x86 --out-dir bw-output cmake --build build/; else build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/; fi
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner
